<header>A short trip to Mustang, Western Nepal</header>
	        <div id="menu">
					<nav>
						<ul>
							<li class="menu"><a href="index.php">Home</a></li>
							<li class="menu"><a href="hometown.php">Description</a></li>
							<li class="menu"><a href="quiz.php">Quiz</a></li>
							<li class="menu"><a href="manage.php">Manage</a></li>
							<li class="menu"><a href="#">Enhancement</a></li>
						</ul>
					</nav>
			</div>
			
			